# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='编号')),
                ('address', models.CharField(max_length=50, verbose_name='日期')),
                ('product_name', models.CharField(max_length=60, verbose_name='商品名称')),
                ('commodity_brand', models.CharField(max_length=50, verbose_name='商品品牌')),
                ('unit_price', models.CharField(max_length=60, verbose_name='单价')),
                ('quantity', models.CharField(max_length=50, verbose_name='数量')),
                ('amount', models.CharField(max_length=60, verbose_name='金额')),
                ('tis', models.CharField(max_length=50, verbose_name='安装情况 /领用人')),
                ('status', models.CharField(max_length=60, verbose_name='状态')),
                ('norc', models.CharField(max_length=50, verbose_name='可领用数')),
            ],
            options={
                'verbose_name': '硬件',
                'verbose_name_plural': '硬件',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='领用人')),
                ('computer', models.CharField(max_length=50, verbose_name='主机箱')),
                ('display', models.CharField(max_length=60, verbose_name='显示器')),
                ('keyboard', models.CharField(max_length=50, verbose_name='键盘')),
                ('mouse', models.CharField(max_length=60, verbose_name='鼠标')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('status', models.CharField(max_length=60, verbose_name='状态')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
    ]
